POST http://localhost:3333/courses
Content-Type: application/json

{
    "title" : "Curso de Fastify"
}

###

GET http://localhost:3333/courses

###

GET http://localhost:3333/courses/b9285bb3-9d78-4bb4-8f17-48abec1d6911

###

DELETE http://localhost:3333/courses/4